-- GENERATED by `registerwatch ddl --write` from src/registerwatch/registers/*.
-- Edit the register modules, not this file; tests fail when the two disagree.
-- Idempotent: safe to re-run.

CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions;
CREATE SCHEMA IF NOT EXISTS registerwatch_private;
REVOKE ALL ON SCHEMA registerwatch_private FROM PUBLIC;
CREATE OR REPLACE FUNCTION registerwatch_private.array_text(text[]) RETURNS text
  LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS $$ SELECT array_to_string($1, ' ') $$;

-- au_acma: Register of licensed interactive wagering service providers
-- Australian Communications and Media Authority (ACMA) (AU) — https://www.acma.gov.au/check-if-gambling-operator-legal
CREATE SCHEMA IF NOT EXISTS au_acma;
COMMENT ON SCHEMA au_acma IS 'Australian Communications and Media Authority (ACMA) (AU): Register of licensed interactive wagering service providers';
CREATE TABLE IF NOT EXISTS au_acma.providers (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  trading_name           text,
  licence_holder         text,
  url                    text,
  licensing_authority    text,
  host                   text
);
ALTER TABLE au_acma.providers ADD COLUMN IF NOT EXISTS trading_name text;
ALTER TABLE au_acma.providers ADD COLUMN IF NOT EXISTS licence_holder text;
ALTER TABLE au_acma.providers ADD COLUMN IF NOT EXISTS url text;
ALTER TABLE au_acma.providers ADD COLUMN IF NOT EXISTS licensing_authority text;
ALTER TABLE au_acma.providers ADD COLUMN IF NOT EXISTS host text;
CREATE UNIQUE INDEX IF NOT EXISTS providers_current_row
  ON au_acma.providers (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS providers_first_seen ON au_acma.providers (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS providers_removed
  ON au_acma.providers (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS providers_current_id
  ON au_acma.providers (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS providers_trading_name_trgm
  ON au_acma.providers USING gin (trading_name extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS providers_licence_holder_trgm
  ON au_acma.providers USING gin (licence_holder extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS providers_url_trgm
  ON au_acma.providers USING gin (url extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS providers_licensing_authority_trgm
  ON au_acma.providers USING gin (licensing_authority extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS providers_host_trgm
  ON au_acma.providers USING gin (host extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS providers_host_lower
  ON au_acma.providers (lower(host)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS providers_host_reverse
  ON au_acma.providers (reverse(lower(host)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW au_acma.current_providers AS
  SELECT trading_name, licence_holder, url, licensing_authority, host, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM au_acma.providers WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE au_acma.providers IS 'providers';

-- be_gc: Licence registers (all classes)
-- Kansspelcommissie / Commission des jeux de hasard (BE) — https://www.gamingcommission.be/
CREATE SCHEMA IF NOT EXISTS be_gc;
COMMENT ON SCHEMA be_gc IS 'Kansspelcommissie / Commission des jeux de hasard (BE): Licence registers (all classes)';
CREATE TABLE IF NOT EXISTS be_gc.online_licences (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  licence_class          text,
  dossier_id             text,
  establishment          text,
  operator               text,
  website                text,
  host                   text,
  decision_date          date,
  publication_date       date,
  expiration_date        date
);
ALTER TABLE be_gc.online_licences ADD COLUMN IF NOT EXISTS licence_class text;
ALTER TABLE be_gc.online_licences ADD COLUMN IF NOT EXISTS dossier_id text;
ALTER TABLE be_gc.online_licences ADD COLUMN IF NOT EXISTS establishment text;
ALTER TABLE be_gc.online_licences ADD COLUMN IF NOT EXISTS operator text;
ALTER TABLE be_gc.online_licences ADD COLUMN IF NOT EXISTS website text;
ALTER TABLE be_gc.online_licences ADD COLUMN IF NOT EXISTS host text;
ALTER TABLE be_gc.online_licences ADD COLUMN IF NOT EXISTS decision_date date;
ALTER TABLE be_gc.online_licences ADD COLUMN IF NOT EXISTS publication_date date;
ALTER TABLE be_gc.online_licences ADD COLUMN IF NOT EXISTS expiration_date date;
CREATE UNIQUE INDEX IF NOT EXISTS online_licences_current_row
  ON be_gc.online_licences (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS online_licences_first_seen ON be_gc.online_licences (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS online_licences_removed
  ON be_gc.online_licences (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS online_licences_current_id
  ON be_gc.online_licences (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS online_licences_licence_class_trgm
  ON be_gc.online_licences USING gin (licence_class extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS online_licences_dossier_id_trgm
  ON be_gc.online_licences USING gin (dossier_id extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS online_licences_establishment_trgm
  ON be_gc.online_licences USING gin (establishment extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS online_licences_operator_trgm
  ON be_gc.online_licences USING gin (operator extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS online_licences_website_trgm
  ON be_gc.online_licences USING gin (website extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS online_licences_host_trgm
  ON be_gc.online_licences USING gin (host extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS online_licences_host_lower
  ON be_gc.online_licences (lower(host)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS online_licences_host_reverse
  ON be_gc.online_licences (reverse(lower(host)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW be_gc.current_online_licences AS
  SELECT licence_class, dossier_id, establishment, operator, website, host, decision_date, publication_date, expiration_date, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM be_gc.online_licences WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE be_gc.online_licences IS 'A+, B+ and F1+ licences: one row per licensed website';

CREATE TABLE IF NOT EXISTS be_gc.establishments (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  licence_class          text,
  dossier_id             text,
  establishment          text,
  owner                  text,
  street_address_nl      text,
  street_address_fr      text,
  postal_code            text,
  commune                text,
  province               text,
  decision_date          date,
  publication_date       date,
  expiration_date        date
);
ALTER TABLE be_gc.establishments ADD COLUMN IF NOT EXISTS licence_class text;
ALTER TABLE be_gc.establishments ADD COLUMN IF NOT EXISTS dossier_id text;
ALTER TABLE be_gc.establishments ADD COLUMN IF NOT EXISTS establishment text;
ALTER TABLE be_gc.establishments ADD COLUMN IF NOT EXISTS owner text;
ALTER TABLE be_gc.establishments ADD COLUMN IF NOT EXISTS street_address_nl text;
ALTER TABLE be_gc.establishments ADD COLUMN IF NOT EXISTS street_address_fr text;
ALTER TABLE be_gc.establishments ADD COLUMN IF NOT EXISTS postal_code text;
ALTER TABLE be_gc.establishments ADD COLUMN IF NOT EXISTS commune text;
ALTER TABLE be_gc.establishments ADD COLUMN IF NOT EXISTS province text;
ALTER TABLE be_gc.establishments ADD COLUMN IF NOT EXISTS decision_date date;
ALTER TABLE be_gc.establishments ADD COLUMN IF NOT EXISTS publication_date date;
ALTER TABLE be_gc.establishments ADD COLUMN IF NOT EXISTS expiration_date date;
CREATE UNIQUE INDEX IF NOT EXISTS establishments_current_row
  ON be_gc.establishments (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS establishments_first_seen ON be_gc.establishments (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS establishments_removed
  ON be_gc.establishments (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS establishments_current_id
  ON be_gc.establishments (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS establishments_licence_class_trgm
  ON be_gc.establishments USING gin (licence_class extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS establishments_dossier_id_trgm
  ON be_gc.establishments USING gin (dossier_id extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS establishments_establishment_trgm
  ON be_gc.establishments USING gin (establishment extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS establishments_owner_trgm
  ON be_gc.establishments USING gin (owner extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS establishments_street_address_nl_trgm
  ON be_gc.establishments USING gin (street_address_nl extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS establishments_street_address_fr_trgm
  ON be_gc.establishments USING gin (street_address_fr extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS establishments_postal_code_trgm
  ON be_gc.establishments USING gin (postal_code extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS establishments_commune_trgm
  ON be_gc.establishments USING gin (commune extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS establishments_province_trgm
  ON be_gc.establishments USING gin (province extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW be_gc.current_establishments AS
  SELECT licence_class, dossier_id, establishment, owner, street_address_nl, street_address_fr, postal_code, commune, province, decision_date, publication_date, expiration_date, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM be_gc.establishments WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE be_gc.establishments IS 'Physical licences: casinos, arcades, betting shops, cafés…';

-- ca_kgc: Interactive permit holders
-- Kahnawà:ke Gaming Commission (CA) — https://gamingcommission.ca/interactive-gaming/permit-holders/
CREATE SCHEMA IF NOT EXISTS ca_kgc;
COMMENT ON SCHEMA ca_kgc IS 'Kahnawà:ke Gaming Commission (CA): Interactive permit holders';
CREATE TABLE IF NOT EXISTS ca_kgc.operators (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  operator               text,
  url                    text,
  host                   text
);
ALTER TABLE ca_kgc.operators ADD COLUMN IF NOT EXISTS operator text;
ALTER TABLE ca_kgc.operators ADD COLUMN IF NOT EXISTS url text;
ALTER TABLE ca_kgc.operators ADD COLUMN IF NOT EXISTS host text;
CREATE UNIQUE INDEX IF NOT EXISTS operators_current_row
  ON ca_kgc.operators (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_first_seen ON ca_kgc.operators (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS operators_removed
  ON ca_kgc.operators (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS operators_current_id
  ON ca_kgc.operators (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_operator_trgm
  ON ca_kgc.operators USING gin (operator extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_url_trgm
  ON ca_kgc.operators USING gin (url extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_host_trgm
  ON ca_kgc.operators USING gin (host extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_host_lower
  ON ca_kgc.operators (lower(host)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_host_reverse
  ON ca_kgc.operators (reverse(lower(host)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW ca_kgc.current_operators AS
  SELECT operator, url, host, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM ca_kgc.operators WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE ca_kgc.operators IS 'operators';

CREATE TABLE IF NOT EXISTS ca_kgc.software_providers (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  name                   text
);
ALTER TABLE ca_kgc.software_providers ADD COLUMN IF NOT EXISTS name text;
CREATE UNIQUE INDEX IF NOT EXISTS software_providers_current_row
  ON ca_kgc.software_providers (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS software_providers_first_seen ON ca_kgc.software_providers (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS software_providers_removed
  ON ca_kgc.software_providers (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS software_providers_current_id
  ON ca_kgc.software_providers (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS software_providers_name_trgm
  ON ca_kgc.software_providers USING gin (name extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW ca_kgc.current_software_providers AS
  SELECT name, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM ca_kgc.software_providers WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE ca_kgc.software_providers IS 'software_providers';

-- ca_on_igo: Regulated iGaming market — operator brands
-- iGaming Ontario (CA-ON) — https://igamingontario.ca/en/player/regulated-igaming-market
CREATE SCHEMA IF NOT EXISTS ca_on_igo;
COMMENT ON SCHEMA ca_on_igo IS 'iGaming Ontario (CA-ON): Regulated iGaming market — operator brands';
CREATE TABLE IF NOT EXISTS ca_on_igo.brands (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  brand                  text,
  website                text,
  host                   text,
  offerings              text[],
  link_text              text
);
ALTER TABLE ca_on_igo.brands ADD COLUMN IF NOT EXISTS brand text;
ALTER TABLE ca_on_igo.brands ADD COLUMN IF NOT EXISTS website text;
ALTER TABLE ca_on_igo.brands ADD COLUMN IF NOT EXISTS host text;
ALTER TABLE ca_on_igo.brands ADD COLUMN IF NOT EXISTS offerings text[];
ALTER TABLE ca_on_igo.brands ADD COLUMN IF NOT EXISTS link_text text;
CREATE UNIQUE INDEX IF NOT EXISTS brands_current_row
  ON ca_on_igo.brands (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_first_seen ON ca_on_igo.brands (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS brands_removed
  ON ca_on_igo.brands (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS brands_current_id
  ON ca_on_igo.brands (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_brand_trgm
  ON ca_on_igo.brands USING gin (brand extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_website_trgm
  ON ca_on_igo.brands USING gin (website extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_host_trgm
  ON ca_on_igo.brands USING gin (host extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_host_lower
  ON ca_on_igo.brands (lower(host)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_host_reverse
  ON ca_on_igo.brands (reverse(lower(host)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_offerings_trgm
  ON ca_on_igo.brands USING gin (registerwatch_private.array_text(offerings) extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_link_text_trgm
  ON ca_on_igo.brands USING gin (link_text extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW ca_on_igo.current_brands AS
  SELECT brand, website, host, offerings, link_text, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM ca_on_igo.brands WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE ca_on_igo.brands IS 'brands';

-- ch_esbk: Blocklist of unauthorised online casino games
-- Eidgenössische Spielbankenkommission (ESBK) (CH) — https://www.esbk.admin.ch/en/unauthorised-online-games
CREATE SCHEMA IF NOT EXISTS ch_esbk;
COMMENT ON SCHEMA ch_esbk IS 'Eidgenössische Spielbankenkommission (ESBK) (CH): Blocklist of unauthorised online casino games';
CREATE TABLE IF NOT EXISTS ch_esbk.blocked_domains (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  domain                 text,
  listed_on              date
);
ALTER TABLE ch_esbk.blocked_domains ADD COLUMN IF NOT EXISTS domain text;
ALTER TABLE ch_esbk.blocked_domains ADD COLUMN IF NOT EXISTS listed_on date;
CREATE UNIQUE INDEX IF NOT EXISTS blocked_domains_current_row
  ON ch_esbk.blocked_domains (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_first_seen ON ch_esbk.blocked_domains (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS blocked_domains_removed
  ON ch_esbk.blocked_domains (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_current_id
  ON ch_esbk.blocked_domains (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_domain_trgm
  ON ch_esbk.blocked_domains USING gin (domain extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_domain_lower
  ON ch_esbk.blocked_domains (lower(domain)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_domain_reverse
  ON ch_esbk.blocked_domains (reverse(lower(domain)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW ch_esbk.current_blocked_domains AS
  SELECT domain, listed_on, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM ch_esbk.blocked_domains WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE ch_esbk.blocked_domains IS 'blocked_domains';

-- ch_gespa: Blocklist of unauthorised lottery and betting sites
-- Gespa — Interkantonale Geldspielaufsicht (CH) — https://www.gespa.ch/en/fighting-illegal-gambling/access-blocking
CREATE SCHEMA IF NOT EXISTS ch_gespa;
COMMENT ON SCHEMA ch_gespa IS 'Gespa — Interkantonale Geldspielaufsicht (CH): Blocklist of unauthorised lottery and betting sites';
CREATE TABLE IF NOT EXISTS ch_gespa.blocked_domains (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  domain                 text,
  well_formed            boolean
);
ALTER TABLE ch_gespa.blocked_domains ADD COLUMN IF NOT EXISTS domain text;
ALTER TABLE ch_gespa.blocked_domains ADD COLUMN IF NOT EXISTS well_formed boolean;
CREATE UNIQUE INDEX IF NOT EXISTS blocked_domains_current_row
  ON ch_gespa.blocked_domains (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_first_seen ON ch_gespa.blocked_domains (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS blocked_domains_removed
  ON ch_gespa.blocked_domains (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_current_id
  ON ch_gespa.blocked_domains (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_domain_trgm
  ON ch_gespa.blocked_domains USING gin (domain extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_domain_lower
  ON ch_gespa.blocked_domains (lower(domain)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_domain_reverse
  ON ch_gespa.blocked_domains (reverse(lower(domain)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW ch_gespa.current_blocked_domains AS
  SELECT domain, well_formed, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM ch_gespa.blocked_domains WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE ch_gespa.blocked_domains IS 'blocked_domains';

-- cz_mf: List of legal gambling operators (Act 186/2016)
-- Ministerstvo financí České republiky (CZ) — https://mf.gov.cz/cs/kontrola-a-regulace/hazardni-hry/prehledy-a-statistiky/prehledy-legalnich-provozovatelu-whiteli
CREATE SCHEMA IF NOT EXISTS cz_mf;
COMMENT ON SCHEMA cz_mf IS 'Ministerstvo financí České republiky (CZ): List of legal gambling operators (Act 186/2016)';
CREATE TABLE IF NOT EXISTS cz_mf.operators (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  operator               text,
  company_id             text,
  seat                   text
);
ALTER TABLE cz_mf.operators ADD COLUMN IF NOT EXISTS operator text;
ALTER TABLE cz_mf.operators ADD COLUMN IF NOT EXISTS company_id text;
ALTER TABLE cz_mf.operators ADD COLUMN IF NOT EXISTS seat text;
CREATE UNIQUE INDEX IF NOT EXISTS operators_current_row
  ON cz_mf.operators (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_first_seen ON cz_mf.operators (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS operators_removed
  ON cz_mf.operators (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS operators_current_id
  ON cz_mf.operators (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_operator_trgm
  ON cz_mf.operators USING gin (operator extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_company_id_trgm
  ON cz_mf.operators USING gin (company_id extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_seat_trgm
  ON cz_mf.operators USING gin (seat extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW cz_mf.current_operators AS
  SELECT operator, company_id, seat, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM cz_mf.operators WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE cz_mf.operators IS 'operators';

CREATE TABLE IF NOT EXISTS cz_mf.permits (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  operator               text,
  game_type              text,
  channel                text,
  final_on               date,
  effective_on           date,
  domains                text[],
  hosts                  text[]
);
ALTER TABLE cz_mf.permits ADD COLUMN IF NOT EXISTS operator text;
ALTER TABLE cz_mf.permits ADD COLUMN IF NOT EXISTS game_type text;
ALTER TABLE cz_mf.permits ADD COLUMN IF NOT EXISTS channel text;
ALTER TABLE cz_mf.permits ADD COLUMN IF NOT EXISTS final_on date;
ALTER TABLE cz_mf.permits ADD COLUMN IF NOT EXISTS effective_on date;
ALTER TABLE cz_mf.permits ADD COLUMN IF NOT EXISTS domains text[];
ALTER TABLE cz_mf.permits ADD COLUMN IF NOT EXISTS hosts text[];
CREATE UNIQUE INDEX IF NOT EXISTS permits_current_row
  ON cz_mf.permits (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS permits_first_seen ON cz_mf.permits (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS permits_removed
  ON cz_mf.permits (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS permits_current_id
  ON cz_mf.permits (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS permits_operator_trgm
  ON cz_mf.permits USING gin (operator extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS permits_game_type_trgm
  ON cz_mf.permits USING gin (game_type extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS permits_channel_trgm
  ON cz_mf.permits USING gin (channel extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS permits_domains_trgm
  ON cz_mf.permits USING gin (registerwatch_private.array_text(domains) extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS permits_hosts_trgm
  ON cz_mf.permits USING gin (registerwatch_private.array_text(hosts) extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW cz_mf.current_permits AS
  SELECT operator, game_type, channel, final_on, effective_on, domains, hosts, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM cz_mf.permits WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE cz_mf.permits IS 'One row per operator × game type × channel; final_on = právní moc';

-- de_ggl: Whitelist of permitted gambling operators
-- Gemeinsame Glücksspielbehörde der Länder (GGL) (DE) — https://www.gluecksspiel-behoerde.de/de/fuer-spielende/uebersicht-erlaubter-anbieter-whitelist
CREATE SCHEMA IF NOT EXISTS de_ggl;
COMMENT ON SCHEMA de_ggl IS 'Gemeinsame Glücksspielbehörde der Länder (GGL) (DE): Whitelist of permitted gambling operators';
CREATE TABLE IF NOT EXISTS de_ggl.permits (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  operator               text,
  gambling_type          text,
  address                text,
  distribution_channel   text,
  sales_area             text,
  authority              text,
  locations              text
);
ALTER TABLE de_ggl.permits ADD COLUMN IF NOT EXISTS operator text;
ALTER TABLE de_ggl.permits ADD COLUMN IF NOT EXISTS gambling_type text;
ALTER TABLE de_ggl.permits ADD COLUMN IF NOT EXISTS address text;
ALTER TABLE de_ggl.permits ADD COLUMN IF NOT EXISTS distribution_channel text;
ALTER TABLE de_ggl.permits ADD COLUMN IF NOT EXISTS sales_area text;
ALTER TABLE de_ggl.permits ADD COLUMN IF NOT EXISTS authority text;
ALTER TABLE de_ggl.permits ADD COLUMN IF NOT EXISTS locations text;
CREATE UNIQUE INDEX IF NOT EXISTS permits_current_row
  ON de_ggl.permits (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS permits_first_seen ON de_ggl.permits (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS permits_removed
  ON de_ggl.permits (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS permits_current_id
  ON de_ggl.permits (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS permits_operator_trgm
  ON de_ggl.permits USING gin (operator extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS permits_gambling_type_trgm
  ON de_ggl.permits USING gin (gambling_type extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS permits_address_trgm
  ON de_ggl.permits USING gin (address extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS permits_distribution_channel_trgm
  ON de_ggl.permits USING gin (distribution_channel extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS permits_sales_area_trgm
  ON de_ggl.permits USING gin (sales_area extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS permits_authority_trgm
  ON de_ggl.permits USING gin (authority extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS permits_locations_trgm
  ON de_ggl.permits USING gin (locations extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW de_ggl.current_permits AS
  SELECT operator, gambling_type, address, distribution_channel, sales_area, authority, locations, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM de_ggl.permits WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE de_ggl.permits IS 'One row per operator and gambling-type permit';

CREATE TABLE IF NOT EXISTS de_ggl.websites (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  operator               text,
  gambling_type          text,
  website                text,
  host                   text,
  first_permit_date      date,
  renewal_date           date
);
ALTER TABLE de_ggl.websites ADD COLUMN IF NOT EXISTS operator text;
ALTER TABLE de_ggl.websites ADD COLUMN IF NOT EXISTS gambling_type text;
ALTER TABLE de_ggl.websites ADD COLUMN IF NOT EXISTS website text;
ALTER TABLE de_ggl.websites ADD COLUMN IF NOT EXISTS host text;
ALTER TABLE de_ggl.websites ADD COLUMN IF NOT EXISTS first_permit_date date;
ALTER TABLE de_ggl.websites ADD COLUMN IF NOT EXISTS renewal_date date;
CREATE UNIQUE INDEX IF NOT EXISTS websites_current_row
  ON de_ggl.websites (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_first_seen ON de_ggl.websites (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS websites_removed
  ON de_ggl.websites (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS websites_current_id
  ON de_ggl.websites (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_operator_trgm
  ON de_ggl.websites USING gin (operator extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_gambling_type_trgm
  ON de_ggl.websites USING gin (gambling_type extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_website_trgm
  ON de_ggl.websites USING gin (website extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_host_trgm
  ON de_ggl.websites USING gin (host extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_host_lower
  ON de_ggl.websites (lower(host)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_host_reverse
  ON de_ggl.websites (reverse(lower(host)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW de_ggl.current_websites AS
  SELECT operator, gambling_type, website, host, first_permit_date, renewal_date, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM de_ggl.websites WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE de_ggl.websites IS 'Websites covered by each permit';

-- ee_emta: List of legal gambling operators
-- Maksu- ja Tolliamet (Estonian Tax and Customs Board) (EE) — https://www.emta.ee/en/business-client/registration-business/gambling-operators/list-legal-gambling-operators
CREATE SCHEMA IF NOT EXISTS ee_emta;
COMMENT ON SCHEMA ee_emta IS 'Maksu- ja Tolliamet (Estonian Tax and Customs Board) (EE): List of legal gambling operators';
CREATE TABLE IF NOT EXISTS ee_emta.operators (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  subtype                text,
  operator               text,
  brand                  text,
  register_url           text
);
ALTER TABLE ee_emta.operators ADD COLUMN IF NOT EXISTS subtype text;
ALTER TABLE ee_emta.operators ADD COLUMN IF NOT EXISTS operator text;
ALTER TABLE ee_emta.operators ADD COLUMN IF NOT EXISTS brand text;
ALTER TABLE ee_emta.operators ADD COLUMN IF NOT EXISTS register_url text;
CREATE UNIQUE INDEX IF NOT EXISTS operators_current_row
  ON ee_emta.operators (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_first_seen ON ee_emta.operators (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS operators_removed
  ON ee_emta.operators (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS operators_current_id
  ON ee_emta.operators (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_subtype_trgm
  ON ee_emta.operators USING gin (subtype extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_operator_trgm
  ON ee_emta.operators USING gin (operator extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_brand_trgm
  ON ee_emta.operators USING gin (brand extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_register_url_trgm
  ON ee_emta.operators USING gin (register_url extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW ee_emta.current_operators AS
  SELECT subtype, operator, brand, register_url, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM ee_emta.operators WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE ee_emta.operators IS 'operators';

CREATE TABLE IF NOT EXISTS ee_emta.websites (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  subtype                text,
  operator               text,
  website                text,
  host                   text
);
ALTER TABLE ee_emta.websites ADD COLUMN IF NOT EXISTS subtype text;
ALTER TABLE ee_emta.websites ADD COLUMN IF NOT EXISTS operator text;
ALTER TABLE ee_emta.websites ADD COLUMN IF NOT EXISTS website text;
ALTER TABLE ee_emta.websites ADD COLUMN IF NOT EXISTS host text;
CREATE UNIQUE INDEX IF NOT EXISTS websites_current_row
  ON ee_emta.websites (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_first_seen ON ee_emta.websites (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS websites_removed
  ON ee_emta.websites (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS websites_current_id
  ON ee_emta.websites (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_subtype_trgm
  ON ee_emta.websites USING gin (subtype extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_operator_trgm
  ON ee_emta.websites USING gin (operator extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_website_trgm
  ON ee_emta.websites USING gin (website extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_host_trgm
  ON ee_emta.websites USING gin (host extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_host_lower
  ON ee_emta.websites (lower(host)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_host_reverse
  ON ee_emta.websites (reverse(lower(host)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW ee_emta.current_websites AS
  SELECT subtype, operator, website, host, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM ee_emta.websites WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE ee_emta.websites IS 'websites';

-- es_dgoj: Operators with a licence for online gambling
-- Dirección General de Ordenación del Juego (DGOJ) (ES) — https://www.ordenacionjuego.es/operadores-juego/operadores-licencia/operadores
CREATE SCHEMA IF NOT EXISTS es_dgoj;
COMMENT ON SCHEMA es_dgoj IS 'Dirección General de Ordenación del Juego (DGOJ) (ES): Operators with a licence for online gambling';
CREATE TABLE IF NOT EXISTS es_dgoj.operators (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  operator               text,
  detail_url             text
);
ALTER TABLE es_dgoj.operators ADD COLUMN IF NOT EXISTS operator text;
ALTER TABLE es_dgoj.operators ADD COLUMN IF NOT EXISTS detail_url text;
CREATE UNIQUE INDEX IF NOT EXISTS operators_current_row
  ON es_dgoj.operators (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_first_seen ON es_dgoj.operators (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS operators_removed
  ON es_dgoj.operators (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS operators_current_id
  ON es_dgoj.operators (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_operator_trgm
  ON es_dgoj.operators USING gin (operator extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_detail_url_trgm
  ON es_dgoj.operators USING gin (detail_url extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW es_dgoj.current_operators AS
  SELECT operator, detail_url, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM es_dgoj.operators WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE es_dgoj.operators IS 'operators';

CREATE TABLE IF NOT EXISTS es_dgoj.websites (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  operator               text,
  website                text,
  host                   text
);
ALTER TABLE es_dgoj.websites ADD COLUMN IF NOT EXISTS operator text;
ALTER TABLE es_dgoj.websites ADD COLUMN IF NOT EXISTS website text;
ALTER TABLE es_dgoj.websites ADD COLUMN IF NOT EXISTS host text;
CREATE UNIQUE INDEX IF NOT EXISTS websites_current_row
  ON es_dgoj.websites (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_first_seen ON es_dgoj.websites (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS websites_removed
  ON es_dgoj.websites (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS websites_current_id
  ON es_dgoj.websites (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_operator_trgm
  ON es_dgoj.websites USING gin (operator extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_website_trgm
  ON es_dgoj.websites USING gin (website extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_host_trgm
  ON es_dgoj.websites USING gin (host extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_host_lower
  ON es_dgoj.websites (lower(host)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_host_reverse
  ON es_dgoj.websites (reverse(lower(host)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW es_dgoj.current_websites AS
  SELECT operator, website, host, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM es_dgoj.websites WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE es_dgoj.websites IS 'websites';

-- fr_anj: Approved online gambling operators
-- Autorité nationale des jeux (ANJ) (FR) — https://anj.fr/offre-de-jeu-et-marche/operateurs-agrees
CREATE SCHEMA IF NOT EXISTS fr_anj;
COMMENT ON SCHEMA fr_anj IS 'Autorité nationale des jeux (ANJ) (FR): Approved online gambling operators';
CREATE TABLE IF NOT EXISTS fr_anj.operators (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  operator               text,
  categories             text[]
);
ALTER TABLE fr_anj.operators ADD COLUMN IF NOT EXISTS operator text;
ALTER TABLE fr_anj.operators ADD COLUMN IF NOT EXISTS categories text[];
CREATE UNIQUE INDEX IF NOT EXISTS operators_current_row
  ON fr_anj.operators (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_first_seen ON fr_anj.operators (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS operators_removed
  ON fr_anj.operators (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS operators_current_id
  ON fr_anj.operators (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_operator_trgm
  ON fr_anj.operators USING gin (operator extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS operators_categories_trgm
  ON fr_anj.operators USING gin (registerwatch_private.array_text(categories) extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW fr_anj.current_operators AS
  SELECT operator, categories, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM fr_anj.operators WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE fr_anj.operators IS 'operators';

CREATE TABLE IF NOT EXISTS fr_anj.websites (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  operator               text,
  website                text,
  host                   text
);
ALTER TABLE fr_anj.websites ADD COLUMN IF NOT EXISTS operator text;
ALTER TABLE fr_anj.websites ADD COLUMN IF NOT EXISTS website text;
ALTER TABLE fr_anj.websites ADD COLUMN IF NOT EXISTS host text;
CREATE UNIQUE INDEX IF NOT EXISTS websites_current_row
  ON fr_anj.websites (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_first_seen ON fr_anj.websites (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS websites_removed
  ON fr_anj.websites (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS websites_current_id
  ON fr_anj.websites (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_operator_trgm
  ON fr_anj.websites USING gin (operator extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_website_trgm
  ON fr_anj.websites USING gin (website extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_host_trgm
  ON fr_anj.websites USING gin (host extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_host_lower
  ON fr_anj.websites (lower(host)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS websites_host_reverse
  ON fr_anj.websites (reverse(lower(host)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW fr_anj.current_websites AS
  SELECT operator, website, host, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM fr_anj.websites WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE fr_anj.websites IS 'websites';

-- gb_ukgc: Public register of gambling businesses
-- Gambling Commission (GB) — https://www.gamblingcommission.gov.uk/public-register/businesses/download
CREATE SCHEMA IF NOT EXISTS gb_ukgc;
COMMENT ON SCHEMA gb_ukgc IS 'Gambling Commission (GB): Public register of gambling businesses';
CREATE TABLE IF NOT EXISTS gb_ukgc.businesses (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  account_number         text,
  licence_account_name   text
);
ALTER TABLE gb_ukgc.businesses ADD COLUMN IF NOT EXISTS account_number text;
ALTER TABLE gb_ukgc.businesses ADD COLUMN IF NOT EXISTS licence_account_name text;
CREATE UNIQUE INDEX IF NOT EXISTS businesses_current_row
  ON gb_ukgc.businesses (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS businesses_first_seen ON gb_ukgc.businesses (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS businesses_removed
  ON gb_ukgc.businesses (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS businesses_current_id
  ON gb_ukgc.businesses (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS businesses_account_number_trgm
  ON gb_ukgc.businesses USING gin (account_number extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS businesses_licence_account_name_trgm
  ON gb_ukgc.businesses USING gin (licence_account_name extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW gb_ukgc.current_businesses AS
  SELECT account_number, licence_account_name, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM gb_ukgc.businesses WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE gb_ukgc.businesses IS 'Licensed businesses (accounts)';

CREATE TABLE IF NOT EXISTS gb_ukgc.licences (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  account_number         text,
  licence_number         text,
  status                 text,
  type                   text,
  activity               text,
  start_date             date,
  end_date               date
);
ALTER TABLE gb_ukgc.licences ADD COLUMN IF NOT EXISTS account_number text;
ALTER TABLE gb_ukgc.licences ADD COLUMN IF NOT EXISTS licence_number text;
ALTER TABLE gb_ukgc.licences ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE gb_ukgc.licences ADD COLUMN IF NOT EXISTS type text;
ALTER TABLE gb_ukgc.licences ADD COLUMN IF NOT EXISTS activity text;
ALTER TABLE gb_ukgc.licences ADD COLUMN IF NOT EXISTS start_date date;
ALTER TABLE gb_ukgc.licences ADD COLUMN IF NOT EXISTS end_date date;
CREATE UNIQUE INDEX IF NOT EXISTS licences_current_row
  ON gb_ukgc.licences (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_first_seen ON gb_ukgc.licences (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS licences_removed
  ON gb_ukgc.licences (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS licences_current_id
  ON gb_ukgc.licences (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_account_number_trgm
  ON gb_ukgc.licences USING gin (account_number extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_licence_number_trgm
  ON gb_ukgc.licences USING gin (licence_number extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_status_trgm
  ON gb_ukgc.licences USING gin (status extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_type_trgm
  ON gb_ukgc.licences USING gin (type extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_activity_trgm
  ON gb_ukgc.licences USING gin (activity extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW gb_ukgc.current_licences AS
  SELECT account_number, licence_number, status, type, activity, start_date, end_date, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM gb_ukgc.licences WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE gb_ukgc.licences IS 'One row per licence and activity; licence_number''s last segment is a version';

CREATE TABLE IF NOT EXISTS gb_ukgc.trading_names (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  account_number         text,
  trading_name           text,
  status                 text
);
ALTER TABLE gb_ukgc.trading_names ADD COLUMN IF NOT EXISTS account_number text;
ALTER TABLE gb_ukgc.trading_names ADD COLUMN IF NOT EXISTS trading_name text;
ALTER TABLE gb_ukgc.trading_names ADD COLUMN IF NOT EXISTS status text;
CREATE UNIQUE INDEX IF NOT EXISTS trading_names_current_row
  ON gb_ukgc.trading_names (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS trading_names_first_seen ON gb_ukgc.trading_names (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS trading_names_removed
  ON gb_ukgc.trading_names (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS trading_names_current_id
  ON gb_ukgc.trading_names (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS trading_names_account_number_trgm
  ON gb_ukgc.trading_names USING gin (account_number extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS trading_names_trading_name_trgm
  ON gb_ukgc.trading_names USING gin (trading_name extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS trading_names_status_trgm
  ON gb_ukgc.trading_names USING gin (status extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW gb_ukgc.current_trading_names AS
  SELECT account_number, trading_name, status, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM gb_ukgc.trading_names WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE gb_ukgc.trading_names IS 'trading_names';

CREATE TABLE IF NOT EXISTS gb_ukgc.domain_names (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  account_number         text,
  domain_name            text,
  status                 text,
  host                   text
);
ALTER TABLE gb_ukgc.domain_names ADD COLUMN IF NOT EXISTS account_number text;
ALTER TABLE gb_ukgc.domain_names ADD COLUMN IF NOT EXISTS domain_name text;
ALTER TABLE gb_ukgc.domain_names ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE gb_ukgc.domain_names ADD COLUMN IF NOT EXISTS host text;
CREATE UNIQUE INDEX IF NOT EXISTS domain_names_current_row
  ON gb_ukgc.domain_names (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domain_names_first_seen ON gb_ukgc.domain_names (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS domain_names_removed
  ON gb_ukgc.domain_names (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS domain_names_current_id
  ON gb_ukgc.domain_names (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domain_names_account_number_trgm
  ON gb_ukgc.domain_names USING gin (account_number extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domain_names_domain_name_trgm
  ON gb_ukgc.domain_names USING gin (domain_name extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domain_names_status_trgm
  ON gb_ukgc.domain_names USING gin (status extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domain_names_host_trgm
  ON gb_ukgc.domain_names USING gin (host extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domain_names_host_lower
  ON gb_ukgc.domain_names (lower(host)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domain_names_host_reverse
  ON gb_ukgc.domain_names (reverse(lower(host)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW gb_ukgc.current_domain_names AS
  SELECT account_number, domain_name, status, host, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM gb_ukgc.domain_names WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE gb_ukgc.domain_names IS 'domain_name is free text as published; host is the parsed hostname or NULL';

-- gr_hgc: Licensees
-- Hellenic Gaming Commission (ΕΕΕΠ) (GR) — https://www.gamingcommission.gov.gr/index.php/forms/licensees
CREATE SCHEMA IF NOT EXISTS gr_hgc;
COMMENT ON SCHEMA gr_hgc IS 'Hellenic Gaming Commission (ΕΕΕΠ) (GR): Licensees';
CREATE TABLE IF NOT EXISTS gr_hgc.licensees (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  company                text,
  licence_type           text
);
ALTER TABLE gr_hgc.licensees ADD COLUMN IF NOT EXISTS company text;
ALTER TABLE gr_hgc.licensees ADD COLUMN IF NOT EXISTS licence_type text;
CREATE UNIQUE INDEX IF NOT EXISTS licensees_current_row
  ON gr_hgc.licensees (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licensees_first_seen ON gr_hgc.licensees (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS licensees_removed
  ON gr_hgc.licensees (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS licensees_current_id
  ON gr_hgc.licensees (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licensees_company_trgm
  ON gr_hgc.licensees USING gin (company extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licensees_licence_type_trgm
  ON gr_hgc.licensees USING gin (licence_type extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW gr_hgc.current_licensees AS
  SELECT company, licence_type, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM gr_hgc.licensees WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE gr_hgc.licensees IS 'licensees';

-- ie_revenue: Registers of gaming licences and bookmakers
-- Revenue Commissioners (IE) — https://www.revenue.ie/en/corporate/information-about-revenue/statistics/excise/licences/gaming-licences.aspx
CREATE SCHEMA IF NOT EXISTS ie_revenue;
COMMENT ON SCHEMA ie_revenue IS 'Revenue Commissioners (IE): Registers of gaming licences and bookmakers';
CREATE TABLE IF NOT EXISTS ie_revenue.gaming_licences (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  licence_ref            text,
  licence_type           text,
  licensee_name          text,
  trading_name           text,
  relevant_officer       text,
  premises_address       text,
  principal_office_address text
);
ALTER TABLE ie_revenue.gaming_licences ADD COLUMN IF NOT EXISTS licence_ref text;
ALTER TABLE ie_revenue.gaming_licences ADD COLUMN IF NOT EXISTS licence_type text;
ALTER TABLE ie_revenue.gaming_licences ADD COLUMN IF NOT EXISTS licensee_name text;
ALTER TABLE ie_revenue.gaming_licences ADD COLUMN IF NOT EXISTS trading_name text;
ALTER TABLE ie_revenue.gaming_licences ADD COLUMN IF NOT EXISTS relevant_officer text;
ALTER TABLE ie_revenue.gaming_licences ADD COLUMN IF NOT EXISTS premises_address text;
ALTER TABLE ie_revenue.gaming_licences ADD COLUMN IF NOT EXISTS principal_office_address text;
CREATE UNIQUE INDEX IF NOT EXISTS gaming_licences_current_row
  ON ie_revenue.gaming_licences (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS gaming_licences_first_seen ON ie_revenue.gaming_licences (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS gaming_licences_removed
  ON ie_revenue.gaming_licences (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS gaming_licences_current_id
  ON ie_revenue.gaming_licences (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS gaming_licences_licence_ref_trgm
  ON ie_revenue.gaming_licences USING gin (licence_ref extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS gaming_licences_licence_type_trgm
  ON ie_revenue.gaming_licences USING gin (licence_type extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS gaming_licences_licensee_name_trgm
  ON ie_revenue.gaming_licences USING gin (licensee_name extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS gaming_licences_trading_name_trgm
  ON ie_revenue.gaming_licences USING gin (trading_name extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS gaming_licences_relevant_officer_trgm
  ON ie_revenue.gaming_licences USING gin (relevant_officer extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS gaming_licences_premises_address_trgm
  ON ie_revenue.gaming_licences USING gin (premises_address extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS gaming_licences_principal_office_address_trgm
  ON ie_revenue.gaming_licences USING gin (principal_office_address extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW ie_revenue.current_gaming_licences AS
  SELECT licence_ref, licence_type, licensee_name, trading_name, relevant_officer, premises_address, principal_office_address, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM ie_revenue.gaming_licences WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE ie_revenue.gaming_licences IS 'gaming_licences';

CREATE TABLE IF NOT EXISTS ie_revenue.bookmakers (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  licence_ref            text,
  licensee_name          text,
  trading_name           text,
  relevant_officer       text,
  place_of_business      text,
  county                 text
);
ALTER TABLE ie_revenue.bookmakers ADD COLUMN IF NOT EXISTS licence_ref text;
ALTER TABLE ie_revenue.bookmakers ADD COLUMN IF NOT EXISTS licensee_name text;
ALTER TABLE ie_revenue.bookmakers ADD COLUMN IF NOT EXISTS trading_name text;
ALTER TABLE ie_revenue.bookmakers ADD COLUMN IF NOT EXISTS relevant_officer text;
ALTER TABLE ie_revenue.bookmakers ADD COLUMN IF NOT EXISTS place_of_business text;
ALTER TABLE ie_revenue.bookmakers ADD COLUMN IF NOT EXISTS county text;
CREATE UNIQUE INDEX IF NOT EXISTS bookmakers_current_row
  ON ie_revenue.bookmakers (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS bookmakers_first_seen ON ie_revenue.bookmakers (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS bookmakers_removed
  ON ie_revenue.bookmakers (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS bookmakers_current_id
  ON ie_revenue.bookmakers (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS bookmakers_licence_ref_trgm
  ON ie_revenue.bookmakers USING gin (licence_ref extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS bookmakers_licensee_name_trgm
  ON ie_revenue.bookmakers USING gin (licensee_name extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS bookmakers_trading_name_trgm
  ON ie_revenue.bookmakers USING gin (trading_name extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS bookmakers_relevant_officer_trgm
  ON ie_revenue.bookmakers USING gin (relevant_officer extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS bookmakers_place_of_business_trgm
  ON ie_revenue.bookmakers USING gin (place_of_business extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS bookmakers_county_trgm
  ON ie_revenue.bookmakers USING gin (county extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW ie_revenue.current_bookmakers AS
  SELECT licence_ref, licensee_name, trading_name, relevant_officer, place_of_business, county, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM ie_revenue.bookmakers WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE ie_revenue.bookmakers IS 'bookmakers';

-- im_gsc: Online gambling licence holders
-- Gambling Supervision Commission (IM) — https://www.isleofmangsc.com/gambling/supervision/online-gambling-licensee-register/
CREATE SCHEMA IF NOT EXISTS im_gsc;
COMMENT ON SCHEMA im_gsc IS 'Gambling Supervision Commission (IM): Online gambling licence holders';
CREATE TABLE IF NOT EXISTS im_gsc.licensees (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  company                text,
  status                 text,
  valid_from             date,
  valid_to               text,
  licence_type           text
);
ALTER TABLE im_gsc.licensees ADD COLUMN IF NOT EXISTS company text;
ALTER TABLE im_gsc.licensees ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE im_gsc.licensees ADD COLUMN IF NOT EXISTS valid_from date;
ALTER TABLE im_gsc.licensees ADD COLUMN IF NOT EXISTS valid_to text;
ALTER TABLE im_gsc.licensees ADD COLUMN IF NOT EXISTS licence_type text;
CREATE UNIQUE INDEX IF NOT EXISTS licensees_current_row
  ON im_gsc.licensees (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licensees_first_seen ON im_gsc.licensees (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS licensees_removed
  ON im_gsc.licensees (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS licensees_current_id
  ON im_gsc.licensees (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licensees_company_trgm
  ON im_gsc.licensees USING gin (company extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licensees_status_trgm
  ON im_gsc.licensees USING gin (status extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licensees_valid_to_trgm
  ON im_gsc.licensees USING gin (valid_to extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licensees_licence_type_trgm
  ON im_gsc.licensees USING gin (licence_type extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW im_gsc.current_licensees AS
  SELECT company, status, valid_from, valid_to, licence_type, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM im_gsc.licensees WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE im_gsc.licensees IS 'valid_to is text: the register writes ''Current''';

CREATE TABLE IF NOT EXISTS im_gsc.domains (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  company                text,
  domain                 text,
  host                   text
);
ALTER TABLE im_gsc.domains ADD COLUMN IF NOT EXISTS company text;
ALTER TABLE im_gsc.domains ADD COLUMN IF NOT EXISTS domain text;
ALTER TABLE im_gsc.domains ADD COLUMN IF NOT EXISTS host text;
CREATE UNIQUE INDEX IF NOT EXISTS domains_current_row
  ON im_gsc.domains (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domains_first_seen ON im_gsc.domains (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS domains_removed
  ON im_gsc.domains (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS domains_current_id
  ON im_gsc.domains (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domains_company_trgm
  ON im_gsc.domains USING gin (company extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domains_domain_trgm
  ON im_gsc.domains USING gin (domain extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domains_domain_lower
  ON im_gsc.domains (lower(domain)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domains_domain_reverse
  ON im_gsc.domains (reverse(lower(domain)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domains_host_trgm
  ON im_gsc.domains USING gin (host extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domains_host_lower
  ON im_gsc.domains (lower(host)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS domains_host_reverse
  ON im_gsc.domains (reverse(lower(host)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW im_gsc.current_domains AS
  SELECT company, domain, host, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM im_gsc.domains WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE im_gsc.domains IS 'domains';

CREATE TABLE IF NOT EXISTS im_gsc.licence_holders (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  name                   text,
  firm_status            text,
  initial_licence_date   date,
  licence_type           text
);
ALTER TABLE im_gsc.licence_holders ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE im_gsc.licence_holders ADD COLUMN IF NOT EXISTS firm_status text;
ALTER TABLE im_gsc.licence_holders ADD COLUMN IF NOT EXISTS initial_licence_date date;
ALTER TABLE im_gsc.licence_holders ADD COLUMN IF NOT EXISTS licence_type text;
CREATE UNIQUE INDEX IF NOT EXISTS licence_holders_current_row
  ON im_gsc.licence_holders (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licence_holders_first_seen ON im_gsc.licence_holders (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS licence_holders_removed
  ON im_gsc.licence_holders (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS licence_holders_current_id
  ON im_gsc.licence_holders (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licence_holders_name_trgm
  ON im_gsc.licence_holders USING gin (name extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licence_holders_firm_status_trgm
  ON im_gsc.licence_holders USING gin (firm_status extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licence_holders_licence_type_trgm
  ON im_gsc.licence_holders USING gin (licence_type extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW im_gsc.current_licence_holders AS
  SELECT name, firm_status, initial_licence_date, licence_type, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM im_gsc.licence_holders WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE im_gsc.licence_holders IS 'The dated XLSX the page links';

-- it_adm: Sites subject to blocking — gambling
-- Agenzia delle Dogane e dei Monopoli (ADM) (IT) — https://www.adm.gov.it/portale/siti-web-inibiti-giochi
CREATE SCHEMA IF NOT EXISTS it_adm;
COMMENT ON SCHEMA it_adm IS 'Agenzia delle Dogane e dei Monopoli (ADM) (IT): Sites subject to blocking — gambling';
CREATE TABLE IF NOT EXISTS it_adm.blocked_domains (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  domain                 text,
  well_formed            boolean
);
ALTER TABLE it_adm.blocked_domains ADD COLUMN IF NOT EXISTS domain text;
ALTER TABLE it_adm.blocked_domains ADD COLUMN IF NOT EXISTS well_formed boolean;
CREATE UNIQUE INDEX IF NOT EXISTS blocked_domains_current_row
  ON it_adm.blocked_domains (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_first_seen ON it_adm.blocked_domains (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS blocked_domains_removed
  ON it_adm.blocked_domains (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_current_id
  ON it_adm.blocked_domains (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_domain_trgm
  ON it_adm.blocked_domains USING gin (domain extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_domain_lower
  ON it_adm.blocked_domains (lower(domain)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_domain_reverse
  ON it_adm.blocked_domains (reverse(lower(domain)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW it_adm.current_blocked_domains AS
  SELECT domain, well_formed, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM it_adm.blocked_domains WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE it_adm.blocked_domains IS 'blocked_domains';

-- pl_mf: Register of domains offering gambling in breach of the Gambling Act
-- Ministerstwo Finansów (PL) — https://hazard.mf.gov.pl/
CREATE SCHEMA IF NOT EXISTS pl_mf;
COMMENT ON SCHEMA pl_mf IS 'Ministerstwo Finansów (PL): Register of domains offering gambling in breach of the Gambling Act';
CREATE TABLE IF NOT EXISTS pl_mf.blocked_domains (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  entry_no               bigint,
  domain                 text,
  added_at_local         text,
  added_on               date
);
ALTER TABLE pl_mf.blocked_domains ADD COLUMN IF NOT EXISTS entry_no bigint;
ALTER TABLE pl_mf.blocked_domains ADD COLUMN IF NOT EXISTS domain text;
ALTER TABLE pl_mf.blocked_domains ADD COLUMN IF NOT EXISTS added_at_local text;
ALTER TABLE pl_mf.blocked_domains ADD COLUMN IF NOT EXISTS added_on date;
CREATE UNIQUE INDEX IF NOT EXISTS blocked_domains_current_row
  ON pl_mf.blocked_domains (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_first_seen ON pl_mf.blocked_domains (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS blocked_domains_removed
  ON pl_mf.blocked_domains (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_current_id
  ON pl_mf.blocked_domains (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_domain_trgm
  ON pl_mf.blocked_domains USING gin (domain extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_domain_lower
  ON pl_mf.blocked_domains (lower(domain)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_domain_reverse
  ON pl_mf.blocked_domains (reverse(lower(domain)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS blocked_domains_added_at_local_trgm
  ON pl_mf.blocked_domains USING gin (added_at_local extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW pl_mf.current_blocked_domains AS
  SELECT entry_no, domain, added_at_local, added_on, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM pl_mf.blocked_domains WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE pl_mf.blocked_domains IS 'blocked_domains';

-- pt_srij: Licensed online gambling entities
-- Serviço de Regulação e Inspeção de Jogos (SRIJ) (PT) — https://www.srij.turismodeportugal.pt/pt/jogo-online/entidades-licenciadas/
CREATE SCHEMA IF NOT EXISTS pt_srij;
COMMENT ON SCHEMA pt_srij IS 'Serviço de Regulação e Inspeção de Jogos (SRIJ) (PT): Licensed online gambling entities';
CREATE TABLE IF NOT EXISTS pt_srij.brands (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  block_id               text,
  title                  text,
  brand                  text,
  website                text,
  host                   text,
  operator               text
);
ALTER TABLE pt_srij.brands ADD COLUMN IF NOT EXISTS block_id text;
ALTER TABLE pt_srij.brands ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE pt_srij.brands ADD COLUMN IF NOT EXISTS brand text;
ALTER TABLE pt_srij.brands ADD COLUMN IF NOT EXISTS website text;
ALTER TABLE pt_srij.brands ADD COLUMN IF NOT EXISTS host text;
ALTER TABLE pt_srij.brands ADD COLUMN IF NOT EXISTS operator text;
CREATE UNIQUE INDEX IF NOT EXISTS brands_current_row
  ON pt_srij.brands (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_first_seen ON pt_srij.brands (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS brands_removed
  ON pt_srij.brands (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS brands_current_id
  ON pt_srij.brands (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_block_id_trgm
  ON pt_srij.brands USING gin (block_id extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_title_trgm
  ON pt_srij.brands USING gin (title extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_brand_trgm
  ON pt_srij.brands USING gin (brand extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_website_trgm
  ON pt_srij.brands USING gin (website extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_host_trgm
  ON pt_srij.brands USING gin (host extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_host_lower
  ON pt_srij.brands (lower(host)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_host_reverse
  ON pt_srij.brands (reverse(lower(host)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS brands_operator_trgm
  ON pt_srij.brands USING gin (operator extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW pt_srij.current_brands AS
  SELECT block_id, title, brand, website, host, operator, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM pt_srij.brands WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE pt_srij.brands IS 'brands';

-- se_si: Licence register
-- Spelinspektionen (SE) — https://www.spelinspektionen.se/licens-o-tillstand/licensregister/
CREATE SCHEMA IF NOT EXISTS se_si;
COMMENT ON SCHEMA se_si IS 'Spelinspektionen (SE): Licence register';
CREATE TABLE IF NOT EXISTS se_si.licences (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  address_1              text,
  address_2              text,
  operator               text,
  shop_id                text,
  redeemer_id            text,
  country                text,
  valid_from             date,
  valid_to               date,
  licence_type           text,
  note                   text,
  note_type              text,
  note_url               text,
  site_address_1         text,
  site_address_2         text,
  site_country           text,
  site_name              text,
  site_postcode          text,
  site_city              text,
  postcode               text,
  city                   text,
  status                 text,
  website                text,
  host                   text
);
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS address_1 text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS address_2 text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS operator text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS shop_id text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS redeemer_id text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS country text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS valid_from date;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS valid_to date;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS licence_type text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS note text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS note_type text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS note_url text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS site_address_1 text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS site_address_2 text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS site_country text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS site_name text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS site_postcode text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS site_city text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS postcode text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS city text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS website text;
ALTER TABLE se_si.licences ADD COLUMN IF NOT EXISTS host text;
CREATE UNIQUE INDEX IF NOT EXISTS licences_current_row
  ON se_si.licences (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_first_seen ON se_si.licences (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS licences_removed
  ON se_si.licences (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS licences_current_id
  ON se_si.licences (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_address_1_trgm
  ON se_si.licences USING gin (address_1 extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_address_2_trgm
  ON se_si.licences USING gin (address_2 extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_operator_trgm
  ON se_si.licences USING gin (operator extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_shop_id_trgm
  ON se_si.licences USING gin (shop_id extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_redeemer_id_trgm
  ON se_si.licences USING gin (redeemer_id extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_country_trgm
  ON se_si.licences USING gin (country extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_licence_type_trgm
  ON se_si.licences USING gin (licence_type extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_note_trgm
  ON se_si.licences USING gin (note extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_note_type_trgm
  ON se_si.licences USING gin (note_type extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_note_url_trgm
  ON se_si.licences USING gin (note_url extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_site_address_1_trgm
  ON se_si.licences USING gin (site_address_1 extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_site_address_2_trgm
  ON se_si.licences USING gin (site_address_2 extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_site_country_trgm
  ON se_si.licences USING gin (site_country extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_site_name_trgm
  ON se_si.licences USING gin (site_name extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_site_postcode_trgm
  ON se_si.licences USING gin (site_postcode extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_site_city_trgm
  ON se_si.licences USING gin (site_city extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_postcode_trgm
  ON se_si.licences USING gin (postcode extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_city_trgm
  ON se_si.licences USING gin (city extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_status_trgm
  ON se_si.licences USING gin (status extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_website_trgm
  ON se_si.licences USING gin (website extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_host_trgm
  ON se_si.licences USING gin (host extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_host_lower
  ON se_si.licences (lower(host)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_host_reverse
  ON se_si.licences (reverse(lower(host)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW se_si.current_licences AS
  SELECT address_1, address_2, operator, shop_id, redeemer_id, country, valid_from, valid_to, licence_type, note, note_type, note_url, site_address_1, site_address_2, site_country, site_name, site_postcode, site_city, postcode, city, status, website, host, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM se_si.licences WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE se_si.licences IS 'Every licence, land-based and online; one row per licence/site';

-- sk_urhh: Granted individual licences
-- Úrad pre reguláciu hazardných hier (ÚRHH) (SK) — https://www.urhh.sk/licencie-2/registre-zoznamy-a-ciselniky/zoznam-udelenych-individualnych-licencii/
CREATE SCHEMA IF NOT EXISTS sk_urhh;
COMMENT ON SCHEMA sk_urhh IS 'Úrad pre reguláciu hazardných hier (ÚRHH) (SK): Granted individual licences';
CREATE TABLE IF NOT EXISTS sk_urhh.licences (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  seq                    integer,
  company                text,
  company_id             text,
  valid_from             date,
  valid_to               date,
  game_name              text,
  game_codes             text[],
  game_types             text
);
ALTER TABLE sk_urhh.licences ADD COLUMN IF NOT EXISTS seq integer;
ALTER TABLE sk_urhh.licences ADD COLUMN IF NOT EXISTS company text;
ALTER TABLE sk_urhh.licences ADD COLUMN IF NOT EXISTS company_id text;
ALTER TABLE sk_urhh.licences ADD COLUMN IF NOT EXISTS valid_from date;
ALTER TABLE sk_urhh.licences ADD COLUMN IF NOT EXISTS valid_to date;
ALTER TABLE sk_urhh.licences ADD COLUMN IF NOT EXISTS game_name text;
ALTER TABLE sk_urhh.licences ADD COLUMN IF NOT EXISTS game_codes text[];
ALTER TABLE sk_urhh.licences ADD COLUMN IF NOT EXISTS game_types text;
CREATE UNIQUE INDEX IF NOT EXISTS licences_current_row
  ON sk_urhh.licences (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_first_seen ON sk_urhh.licences (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS licences_removed
  ON sk_urhh.licences (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS licences_current_id
  ON sk_urhh.licences (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_company_trgm
  ON sk_urhh.licences USING gin (company extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_company_id_trgm
  ON sk_urhh.licences USING gin (company_id extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_game_name_trgm
  ON sk_urhh.licences USING gin (game_name extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_game_codes_trgm
  ON sk_urhh.licences USING gin (registerwatch_private.array_text(game_codes) extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS licences_game_types_trgm
  ON sk_urhh.licences USING gin (game_types extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW sk_urhh.current_licences AS
  SELECT seq, company, company_id, valid_from, valid_to, game_name, game_codes, game_types, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM sk_urhh.licences WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE sk_urhh.licences IS 'licences';

-- us_nj_dge: Internet gaming sites authorised to operate
-- New Jersey Division of Gaming Enforcement (US-NJ) — https://www.njoag.gov/about/divisions-and-offices/division-of-gaming-enforcement-home/internet-gaming-sites/
CREATE SCHEMA IF NOT EXISTS us_nj_dge;
COMMENT ON SCHEMA us_nj_dge IS 'New Jersey Division of Gaming Enforcement (US-NJ): Internet gaming sites authorised to operate';
CREATE TABLE IF NOT EXISTS us_nj_dge.internet_gaming_sites (
  id                     bigserial PRIMARY KEY,
  row_hash               bytea  NOT NULL,
  first_seen_snapshot_id bigint NOT NULL REFERENCES public.raw_snapshots(id),
  last_seen_snapshot_id  bigint NOT NULL REFERENCES public.raw_snapshots(id),
  removed_snapshot_id    bigint REFERENCES public.raw_snapshots(id),
  first_seen_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at           timestamptz NOT NULL DEFAULT now(),
  removed_at             timestamptz,
  licensee               text,
  site                   text,
  host                   text,
  status                 text
);
ALTER TABLE us_nj_dge.internet_gaming_sites ADD COLUMN IF NOT EXISTS licensee text;
ALTER TABLE us_nj_dge.internet_gaming_sites ADD COLUMN IF NOT EXISTS site text;
ALTER TABLE us_nj_dge.internet_gaming_sites ADD COLUMN IF NOT EXISTS host text;
ALTER TABLE us_nj_dge.internet_gaming_sites ADD COLUMN IF NOT EXISTS status text;
CREATE UNIQUE INDEX IF NOT EXISTS internet_gaming_sites_current_row
  ON us_nj_dge.internet_gaming_sites (row_hash) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS internet_gaming_sites_first_seen ON us_nj_dge.internet_gaming_sites (first_seen_snapshot_id);
CREATE INDEX IF NOT EXISTS internet_gaming_sites_removed
  ON us_nj_dge.internet_gaming_sites (removed_snapshot_id) WHERE removed_snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS internet_gaming_sites_current_id
  ON us_nj_dge.internet_gaming_sites (id) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS internet_gaming_sites_licensee_trgm
  ON us_nj_dge.internet_gaming_sites USING gin (licensee extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS internet_gaming_sites_site_trgm
  ON us_nj_dge.internet_gaming_sites USING gin (site extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS internet_gaming_sites_host_trgm
  ON us_nj_dge.internet_gaming_sites USING gin (host extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS internet_gaming_sites_host_lower
  ON us_nj_dge.internet_gaming_sites (lower(host)) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS internet_gaming_sites_host_reverse
  ON us_nj_dge.internet_gaming_sites (reverse(lower(host)) text_pattern_ops) WHERE removed_snapshot_id IS NULL;
CREATE INDEX IF NOT EXISTS internet_gaming_sites_status_trgm
  ON us_nj_dge.internet_gaming_sites USING gin (status extensions.gin_trgm_ops) WHERE removed_snapshot_id IS NULL;
CREATE OR REPLACE VIEW us_nj_dge.current_internet_gaming_sites AS
  SELECT licensee, site, host, status, first_seen_at, last_seen_at, id, first_seen_snapshot_id
    FROM us_nj_dge.internet_gaming_sites WHERE removed_snapshot_id IS NULL;
COMMENT ON TABLE us_nj_dge.internet_gaming_sites IS 'internet_gaming_sites';
